docking_mode: cpu
tools:
  vina_cpu_path: tools/vina_1.2.7_win.exe
  vina_gpu_path: tools/vina-gpu.exe
docking:
  box:
    center: [3.229, 6.273, -12.98]
    size: [9, 9, 9]
  exhaustiveness: 8
  num_modes: 9
  energy_range: 3
